FROM debian:jessie

RUN apt-get update && apt-get install -y \
            wget \
            && \
    apt-get -y autoclean && apt-get -y autoremove

# following https://yandex.com/support/disk/cli-clients.html#cli-install, removed sudo before commands
RUN echo "deb http://repo.yandex.ru/yandex-disk/deb/ stable main" | tee -a /etc/apt/sources.list.d/yandex.list > /dev/null && \
    wget http://repo.yandex.ru/yandex-disk/YANDEX-DISK-KEY.GPG -O- | apt-key add - && \
    apt-get update && apt-get install -y yandex-disk


RUN groupadd theuser && useradd --create-home --gid theuser --uid 1000 theuser
WORKDIR /home/theuser
ENV HOME /home/theuser
USER theuser


CMD "yandex-disk --no-daemon"

